version: '2'

services:
  payments-api:
    image: docker.artifactory.reform.hmcts.net/common-components/payments-api
    command: --wait-for-database 30
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payments-database:5432/payment
      - auth.provider.service.client.baseUrl=http://service-auth-provider-api:8080/
      - auth.idam.client.baseUrl=http://idam-api:8080/
      - gov.pay.url=http://gov-pay-stub:8080
    ports:
     - 8080:8080
    links:
     - payments-database
     - service-auth-provider-api
     - idam-api
     - gov-pay-stub
    depends_on:
     - payments-database
     - service-auth-provider-api
     - idam-api
     - gov-pay-stub

  payments-database:
    image: docker.artifactory.reform.hmcts.net/common-components/payments-database
    ports:
      - 5430:5432

  gov-pay-stub:
    build:
      context: src/test/resources/gov-pay-stub/
    volumes:
      - ./src/test/resources/gov-pay-stub/mappings:/mappings
    ports:
      - 8083:8080

  # IDAM
  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://idam-database:5432/idam
      - idam.testing-support.enabled=true
    ports:
      - 8084:8080
    links:
     - idam-database
    depends_on:
     - idam-database

  idam-database:
    image: docker.artifactory.reform.hmcts.net/auth/idam-database
    ports:
      - 5434:5432

  # service-auth-provider
  service-auth-provider-api:
    image: docker.artifactory.reform.hmcts.net/auth/service-auth-provider-api
    environment:
      - auth.provider.service.server.jwtKey=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      - auth.provider.service.server.microserviceKeys.divorce=AAAAAAAAAAAAAAAA
      - auth.provider.service.testing-support.enabled=true
    ports:
      - 8085:8080

